# Generated by Django 3.2.9 on 2022-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220419_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='result_page',
        ),
        migrations.AddField(
            model_name='choice',
            name='result_text',
            field=models.TextField(default=''),
        ),
    ]
