# Generated by Django 3.2.9 on 2022-04-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220419_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
