# Generated by Django 3.2.9 on 2022-04-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_scores_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='last_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.choice'),
        ),
    ]
