# Generated by Django 3.2.9 on 2022-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_annotation_alter_scores_last_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='scores',
            name='dictionary',
            field=models.ManyToManyField(to='main.Term'),
        ),
    ]
