# Generated by Django 3.2.9 on 2022-04-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220426_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'verbose_name': 'Аннотация', 'verbose_name_plural': 'Аннотации'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Выбор', 'verbose_name_plural': 'Выборы'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': 'Счет пользователя', 'verbose_name_plural': 'Счет пользователей'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name': 'Термин', 'verbose_name_plural': 'Термины'},
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annot_id',
            field=models.IntegerField(verbose_name='Id аннотации'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='result',
            field=models.BooleanField(verbose_name='Продолжает игру'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='cur_score',
            field=models.IntegerField(default=0, verbose_name='Текущий счет'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='max_score',
            field=models.IntegerField(default=0, verbose_name='Максимальный счет'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(verbose_name='Определение'),
        ),
        migrations.AlterField(
            model_name='term',
            name='word',
            field=models.TextField(verbose_name='Термин'),
        ),
    ]
