# Generated by Django 3.2.9 on 2022-04-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220428_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='term',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
