# Generated by Django 3.2.9 on 2022-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220428_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='item',
            field=models.BooleanField(default=False),
        ),
    ]
