# Generated by Django 3.2.9 on 2022-04-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_term_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
            ],
        ),
        migrations.RemoveField(
            model_name='term',
            name='item',
        ),
        migrations.AlterField(
            model_name='term',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='term',
            name='source',
            field=models.TextField(blank=True, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='scores',
            name='items',
            field=models.ManyToManyField(to='main.Item'),
        ),
    ]
